kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    image: &image kindest/node:v1.28.0
  - role: worker
    image: *image
  - role: worker
    image: *image
  - role: worker
    image: *image
  - role: worker
    image: *image
