apiVersion: v1
kind: Service
metadata:
  name: mariadb
  labels:
    app: mariadb
spec:
  ports:
    - port: 3306
      name: mariadb
  # it works with a non headless service
  clusterIP: None
  selector:
    app: mariadb
