apiVersion: v1
kind: Service
metadata:
  name: maxscale-rw-split
  labels:
    app.kubernetes.io/instance: maxscale-rw-split
    app.kubernetes.io/name: maxscale-rw-split
spec:
  selector:
    app.kubernetes.io/instance: maxscale-rw-split
    app.kubernetes.io/name: maxscale-rw-split
  ports:
  - name: write
    port: 3306
    protocol: TCP
    targetPort: 3306
  - name: gui
    port: 8989
    protocol: TCP
    targetPort: 8989