apiVersion: v1
kind: Service
metadata:
  name: exporter
  labels:
    app.kubernetes.io/instance: exporter
    app.kubernetes.io/name: exporter
spec:
  selector:
    app.kubernetes.io/instance: exporter
    app.kubernetes.io/name: exporter
  ports:
  - name: metrics
    port: 9104
    protocol: TCP
    targetPort: 9104
