apiVersion: mariadb.mmontes.io/v1alpha1
kind: Grant
metadata:
  name: client
spec:
  mariaDbRef:
    name: mariadb-repl
  privileges:
    - "SELECT"
    - "INSERT"
    - "UPDATE"
    - "DELETE"
  database: "*"
  table: "*"
  username: client
  grantOption: false
  host: maxscale.default.svc.cluster.local
  retryInterval: 5s