apiVersion: mariadb.mmontes.io/v1alpha1
kind: User
metadata:
  name: client
spec:
  mariaDbRef:
    name: mariadb-repl
  passwordSecretKeyRef:
    name: mariadb
    key: password
  maxUserConnections: 20
  host: maxscale.default.svc.cluster.local
  retryInterval: 5s