apiVersion: mariadb.mmontes.io/v1alpha1
kind: Grant
metadata:
  name: maxscale
spec:
  mariaDbRef:
    name: mariadb-repl
  privileges:
    - "SELECT"
  database: "mysql"
  table: "*"
  username: maxscale
  grantOption: false
  host: "%"
  retryInterval: 5s