apiVersion: mariadb.mmontes.io/v1alpha1
kind: Grant
metadata:
  name: maxscale
spec:
  mariaDbRef:
    name: mariadb-repl
  privileges:
    - "SELECT"
  database: "*" # TODO: restrict based on: https://mariadb.com/kb/en/mariadb-maxscale-2308-setting-up-mariadb-maxscale/#creating-a-user-account-for-maxscale
  table: "*"
  username: maxscale
  grantOption: false
  host: "%"
  retryInterval: 5s