apiVersion: v1
kind: Service
metadata:
  name: maxscale-api
  labels:
    app.kubernetes.io/instance: maxscale-api
    app.kubernetes.io/name: maxscale-api
  annotations:
    metallb.universe.tf/loadBalancerIPs: $CIDR_PREFIX.0.202
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/instance: maxscale-api
    app.kubernetes.io/name: maxscale-api
  ports:
  - name: write
    port: 3306
    protocol: TCP
    targetPort: 3306
  - name: read
    port: 3307
    protocol: TCP
    targetPort: 3307
  - name: gui
    port: 8989
    protocol: TCP
    targetPort: 8989