apiVersion: v1
kind: Service
metadata:
  name: maxscale-0-lb
  namespace: default
  annotations:
    metallb.universe.tf/loadBalancerIPs: $CIDR_PREFIX.0.210
spec:
  ports:
  - name: write
    port: 3306
    protocol: TCP
    targetPort: 3306
  - name: read
    port: 3307
    protocol: TCP
    targetPort: 3307
  - name: gui
    port: 8989
    protocol: TCP
    targetPort: 8989
  selector:
    app.kubernetes.io/instance: maxscale
    app.kubernetes.io/name: maxscale
    statefulset.kubernetes.io/pod-name: maxscale-0  
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: maxscale-1-lb
  namespace: default
  annotations:
    metallb.universe.tf/loadBalancerIPs: $CIDR_PREFIX.0.211
spec:
  ports:
  - name: write
    port: 3306
    protocol: TCP
    targetPort: 3306
  - name: read
    port: 3307
    protocol: TCP
    targetPort: 3307
  - name: gui
    port: 8989
    protocol: TCP
    targetPort: 8989
  selector:
    app.kubernetes.io/instance: maxscale
    app.kubernetes.io/name: maxscale
    statefulset.kubernetes.io/pod-name: maxscale-1 
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: maxscale-2-lb
  namespace: default
  annotations:
    metallb.universe.tf/loadBalancerIPs: $CIDR_PREFIX.0.212
spec:
  ports:
  - name: write
    port: 3306
    protocol: TCP
    targetPort: 3306
  - name: read
    port: 3307
    protocol: TCP
    targetPort: 3307
  - name: gui
    port: 8989
    protocol: TCP
    targetPort: 8989
  selector:
    app.kubernetes.io/instance: maxscale
    app.kubernetes.io/name: maxscale
    statefulset.kubernetes.io/pod-name: maxscale-2
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: maxscale-3-lb
  namespace: default
  annotations:
    metallb.universe.tf/loadBalancerIPs: $CIDR_PREFIX.0.213
spec:
  ports:
  - name: write
    port: 3306
    protocol: TCP
    targetPort: 3306
  - name: read
    port: 3307
    protocol: TCP
    targetPort: 3307
  - name: gui
    port: 8989
    protocol: TCP
    targetPort: 8989
  selector:
    app.kubernetes.io/instance: maxscale
    app.kubernetes.io/name: maxscale
    statefulset.kubernetes.io/pod-name: maxscale-3
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: maxscale
  labels:
    app.kubernetes.io/instance: maxscale
    app.kubernetes.io/name: maxscale
  annotations:
    metallb.universe.tf/loadBalancerIPs: $CIDR_PREFIX.0.214
spec:
  ports:
  - name: write
    port: 3306
    protocol: TCP
    targetPort: 3306
  - name: read
    port: 3307
    protocol: TCP
    targetPort: 3307
  - name: gui
    port: 8989
    protocol: TCP
    targetPort: 8989
  selector:
    app.kubernetes.io/instance: maxscale
    app.kubernetes.io/name: maxscale
  type: LoadBalancer