apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-scripts
data:
  start.sh: |
    #!/bin/bash

    set -e

    HOSTNAME=$(hostname)
    INDEX=${HOSTNAME##*-}
    GALERA_CONFIG_FILE=/etc/mysql/mariadb.conf.d/galera.cnf
    GALERA_STATE_FILE=/var/lib/mysql/grastate.dat
    if [ -z "$ENTRYPOINT" ]; then
        ENTRYPOINT="/usr/local/bin/docker-entrypoint.sh"
    fi

    # MariaDB Galera config file
    cat <<EOF | tee ${GALERA_CONFIG_FILE} 
    [mysqld]
    bind-address=0.0.0.0
    default_storage_engine=InnoDB
    binlog_format=row
    innodb_autoinc_lock_mode=2

    # Galera cluster configuration
    wsrep_on=ON
    wsrep_provider=/usr/lib/galera/libgalera_smm.so
    wsrep_cluster_address="gcomm://mariadb-0.mariadb.default.svc.cluster.local,mariadb-1.mariadb.default.svc.cluster.local"
    wsrep_cluster_name="mariadb-galera-cluster"
    wsrep_sst_method=rsync

    # Cluster node configuration
    wsrep_node_address="${HOSTNAME}.mariadb.default.svc.cluster.local"
    wsrep_node_name="${HOSTNAME}"
    EOF

    # Bootstrap failed container
    if [ -f "$GALERA_STATE_FILE" ]; then 
      sed -i  "s/safe_to_bootstrap: 0/safe_to_bootstrap: 1/" "$GALERA_STATE_FILE" 
    fi

    if [ "$INDEX" = "0" ]; then 
        bash -c "$ENTRYPOINT mariadbd --wsrep-new-cluster"
    else
        bash -c "$ENTRYPOINT mariadbd"
    fi
