apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-scripts
data:
  start.sh: |
    #!/bin/bash

    set -e

    HOSTNAME=$(hostname)
    STATEFULSET_INDEX=${HOSTNAME##*-}
    if [ -z "$ENTRYPOINT" ]; then
      ENTRYPOINT="/usr/local/bin/docker-entrypoint.sh"
    fi
    if [ -z "$GALERA_CONFIG_FILE" ]; then
      GALERA_CONFIG_FILE=/etc/mysql/mariadb.conf.d/galera.cnf
    fi
    if [ -z "$GALERA_STATE_FILE" ]; then 
      GALERA_STATE_FILE=/var/lib/mysql/grastate.dat
    fi
    if [ "$STATEFULSET_INDEX" = "0" ]; then
      WSREP_NEW_CLUSTER="ON"
    else
      WSREP_NEW_CLUSTER="OFF"
    fi

    # MariaDB Galera config file
    cat <<EOF | tee ${GALERA_CONFIG_FILE} 
    [mysqld]
    bind-address=0.0.0.0
    default_storage_engine=InnoDB
    binlog_format=row
    innodb_autoinc_lock_mode=2

    # Galera cluster configuration
    wsrep_new_cluster="$WSREP_NEW_CLUSTER"
    wsrep_on=ON
    wsrep_provider=/usr/lib/galera/libgalera_smm.so
    wsrep_cluster_address="gcomm://mariadb-0.mariadb-headless.default.svc.cluster.local,mariadb-1.mariadb-headless.default.svc.cluster.local,mariadb-2.mariadb-headless.default.svc.cluster.local"
    wsrep_cluster_name="mariadb-galera-cluster"
    wsrep_sst_method=rsync

    # Cluster node configuration
    wsrep_node_address="$HOSTNAME.mariadb-headless.default.svc.cluster.local"
    wsrep_node_name="$HOSTNAME"
    EOF

    # Bootstrap failed container
    if [ -f "$GALERA_STATE_FILE" ]; then 
      sed -i  "s/safe_to_bootstrap: 0/safe_to_bootstrap: 1/" "$GALERA_STATE_FILE" 
    fi

    bash -c "$ENTRYPOINT mariadbd"
