apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/component: database
    app.kubernetes.io/instance: mariadb
    app.kubernetes.io/name: mariadb
  name: mariadb
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/component: database
      app.kubernetes.io/instance: mariadb
      app.kubernetes.io/name: mariadb
  serviceName: mariadb-headless
  template:
    metadata:
      labels:
        app.kubernetes.io/component: database
        app.kubernetes.io/instance: mariadb
        app.kubernetes.io/name: mariadb
      name: mariadb
    spec:
      serviceAccountName: mariadb
      initContainers:
        - name: mariadb-init
          image: nicolaka/netshoot:v0.7
          imagePullPolicy: IfNotPresent
          command:
            - bash
            - -c
            - /scripts/init.sh
          env:
            - name: MARIADB_ROOT_PASSWORD
              value: mariadb
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: CLUSTER
              value: cluster.local
          volumeMounts:
            - mountPath: /etc/mysql/mariadb.conf.d
              name: config
            - mountPath: /var/lib/mysql
              name: storage
            - mountPath: /scripts
              name: scripts
      containers:
        - name: mariadb
          image: mariadb:10.6.8
          imagePullPolicy: IfNotPresent
          env:
            - name: MYSQL_TCP_PORT
              value: "3306"
            - name: MARIADB_ROOT_PASSWORD
              value: mariadb
            - name: MARIADB_DATABASE
              value: mariadb
            - name: MARIADB_USER
              value: mariadb
            - name: MARIADB_PASSWORD
              value: mariadb
          livenessProbe:
            exec:
              command:
                - bash
                - -c
                - mysql -u root -p${MARIADB_ROOT_PASSWORD} -e "SHOW STATUS WHERE variable_name = 'wsrep_ready';"
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - bash
                - -ec
                - mysql -u root -p${MARIADB_ROOT_PASSWORD} -e "SELECT 1;"
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
          ports:
            - containerPort: 3306
              protocol: TCP
            - containerPort: 4444
              protocol: TCP
            - containerPort: 4567
              protocol: TCP
            - containerPort: 4568
              protocol: TCP
          resources:
            limits:
              cpu: 300m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi
          volumeMounts:
            - mountPath: /etc/mysql/mariadb.conf.d
              name: config
            - mountPath: /var/lib/mysql
              name: storage
            - mountPath: /scripts
              name: scripts
      volumes:
        - name: scripts
          secret:
            secretName: mariadb-scripts
            defaultMode: 0777
        - name: config
          emptyDir: {}
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: storage
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 100Mi
        storageClassName: standard
