apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: maxscale
spec:
  serviceName: maxscale-internal
  podManagementPolicy: Parallel
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/instance: maxscale
      app.kubernetes.io/name: maxscale
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: maxscale
        app.kubernetes.io/name: maxscale
    spec:
      containers:
        - name: maxscale
          image: mariadb/maxscale:23.08
          command: 
            - maxscale
          args:
            - --config
            - /etc/config/ha.cnf
            - -dU
            - maxscale
            - -l
            - stdout
          ports:
            - name: write
              containerPort: 3306
            - name: read
              containerPort: 3307
            - name: gui
              containerPort: 8989
          livenessProbe:
            httpGet:
              path: /
              port: 8989
          readinessProbe:
            httpGet:
              path: /
              port: 8989
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 1000m
              memory: 500Mi
          volumeMounts:
            - name: config
              mountPath: /etc/config
            - name: storage
              mountPath: /var/lib/maxscale
      volumes:
        - name: config
          secret:
            secretName: config
  volumeClaimTemplates:
    - metadata:
        name: storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 100M