apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: mariadb
    app.kubernetes.io/name: mariadb
  annotations:
    metallb.universe.tf/loadBalancerIPs: 172.18.0.20
  name: mariadb
spec:
  type: LoadBalancer
  ports:
    - name: mysql
      port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    app.kubernetes.io/instance: mariadb
    app.kubernetes.io/name: mariadb
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: mariadb
    app.kubernetes.io/name: mariadb
  name: mariadb-internal
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/instance: mariadb
    app.kubernetes.io/name: mariadb
