apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/instance: mariadb
    app.kubernetes.io/name: mariadb
  name: mariadb
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: mariadb
      app.kubernetes.io/name: mariadb
  serviceName: mariadb-internal
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: mariadb
        app.kubernetes.io/name: mariadb
      name: mariadb
    spec:
      containers:
        - name: mariadb
          image: mariadb:10.11.3
          imagePullPolicy: IfNotPresent
          env:
            - name: MYSQL_TCP_PORT
              value: "3306"
            - name: MARIADB_ROOT_PASSWORD
              value: mariadb
            - name: MARIADB_ROOT_HOST
              value: "%"
            - name: MARIADB_DATABASE
              value: mariadb
            - name: MARIADB_USER
              value: mariadb
            - name: MARIADB_PASSWORD
              value: mariadb
          ports:
            - containerPort: 3306
              protocol: TCP
          resources:
            limits:
              cpu: 300m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: storage
            - mountPath: /etc/mysql/mariadb.conf.d
              name: mycnf
            - mountPath: /etc/pki
              name: pki
            - mountPath: /etc/pki/ca
              name: ca
      volumes:
        - name: mycnf
          configMap:
            name: mycnf
        - name: ca
          projected:
            sources:
            - secret:
                name: client-ca
                items:
                  - key: tls.crt
                    path: client.crt
        - name: pki
          projected:
            sources:
              - secret:
                  name: server
                  items:
                    - key: tls.crt
                      path: server.crt
                    - key: tls.key
                      path: server.key
              - secret:
                  name: client
                  items:
                    - key: tls.crt
                      path: client.crt
                    - key: tls.key
                      path: client.key
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: storage
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 100Mi
        storageClassName: standard