apiVersion: mariadb.mmontes.io/v1alpha1
kind: User
metadata:
  name: client
spec:
  mariaDbRef:
    name: mariadb-repl
  passwordSecretKeyRef:
    name: mariadb
    key: password
  maxUserConnections: 20
  # TODO: restrict host to: maxscale-conn.default.svc.cluster.local. Getting this warning
  # [Warning] 'user' entry 'client@maxscale-conn.default.svc.cluster.local' ignored in --skip-name-resolve mode.
  host: "%" 
  retryInterval: 5s