apiVersion: mariadb.mmontes.io/v1alpha1
kind: Grant
metadata:
  name: monitor
spec:
  mariaDbRef:
    name: mariadb-repl
  # See:
  # https://mariadb.com/kb/en/mariadb-maxscale-2308-configuring-the-mariadb-monitor/
  # https://mariadb.com/kb/en/mariadb-maxscale-2308-mariadb-monitor/#cluster-manipulation-grants
  privileges:
    - "RELOAD"
    - "REPLICATION CLIENT"
    - "SLAVE MONITOR"
    - "SUPER"
    # failover
    - "REPLICATION SLAVE ADMIN"
    - "REPLICATION SLAVE"
    - "READ_ONLY ADMIN"
    - "BINLOG ADMIN"
    - "CONNECTION ADMIN" 
  database: "*"
  table: "*"
  username: monitor
  grantOption: false
  host: "%"
  retryInterval: 5s