apiVersion: mariadb.mmontes.io/v1alpha1
kind: Grant
metadata:
  name: monitor
spec:
  mariaDbRef:
    name: mariadb-repl
  # See:
  # https://mariadb.com/kb/en/mariadb-maxscale-2308-configuring-the-mariadb-monitor/
  # https://mariadb.com/kb/en/mariadb-maxscale-2308-mariadb-monitor/#cluster-manipulation-grants
  # https://mariadb.com/kb/en/mariadb-maxscale-2308-mariadb-monitor/#cluster-manipulation-operations
  privileges:
    - "BINLOG ADMIN"
    - "CONNECTION ADMIN"
    - "EVENT"
    - "PROCESS"
    - "PROCESS"
    - "READ_ONLY ADMIN"
    - "RELOAD"
    - "REPLICA MONITOR"
    - "REPLICATION CLIENT"
    - "REPLICATION SLAVE ADMIN"
    - "REPLICATION SLAVE"
    - "SELECT"
    - "SET USER"
    - "SHOW DATABASES"
    - "SLAVE MONITOR"
    - "SUPER"
  database: "*"
  table: "*"
  username: monitor
  grantOption: false
  host: "%"
  retryInterval: 5s