apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-galera-config
data:
  my.cnf: |
    [mariadb]
    bind-address=*
    default_storage_engine=InnoDB
    binlog_format=row
    innodb_autoinc_lock_mode=2
    max_allowed_packet=256M

