apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mariadb-galera
rules:
- apiGroups:
  - k8s.mariadb.com
  resources:
  - mariadbs
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mariadb-galera
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mariadb-galera
subjects:
- kind: ServiceAccount
  name: mariadb-galera
  namespace: galera-init-job
